### ISSUE TITLE
Indentation width

### ISSUE THREAD

**Issue by jameskolce** [lijunsong/pollen-mode#15]
Hello, I just started to use Emacs and pollen-mode but when I hit TAB I'm getting 8 spaces and I would like to get only 2, so I was wondering how to change that if possible. 
Thanks!

**Comment by ylluminarious** [comment]
Put `(setq tab-width 2)` in your init files or do `M-x customize-variable RET tab-width RET` and put `2` in the input field instead of `8`.

**Comment by jameskolce** [comment]
Thank you so much @ylluminarious, I already had `setq tab-width 2` on my init file but it wasn't working, so I did the second option and looks like is good now. Although the is an issue but I don't know if is actually a problem or just a mistake in my formating; It looks like it's inferring the indentation in ways that I don't expect instead of always using 2 spaces.

For example, I have this:

```
◊title{Lorem ipsum dolor sit amet, consectetur adipiscing elit
◊small{Lorem ipsum dolor sit amet, consectetur adipiscing elit}
}
```

And these are all the different indentations I get:

![image](https://cloud.githubusercontent.com/assets/2559808/21029697/35cd69f4-bd58-11e6-8fdb-c656c84ffe8f.png)

![image](https://cloud.githubusercontent.com/assets/2559808/21029743/61d762d4-bd58-11e6-906d-f5b3d927dc1f.png)

![image](https://cloud.githubusercontent.com/assets/2559808/21029774/9d1e59b0-bd58-11e6-83ed-976bc471756c.png)

This is the correct one, but I have to add the content in a new line and indent it, so the second line gets indented correctly.

![image](https://cloud.githubusercontent.com/assets/2559808/21029793/b328fb8e-bd58-11e6-8cae-97752727f709.png)

In other places looks like it works correctly. But I can live with that, I just have to organize the code where tabs work. If that's an expected behavior then this issue can be closed. Thank you again.

**Comment by ylluminarious** [comment]
@jameskolce Hmm, I'm not sure about that; maybe @lijunsong knows the correct behavior here?

**Comment by lijunsong** [comment]
Hi @jameskolce , 

(I am not sure why I didn't get notification until now.)

@ylluminarious got it partially right. Emacs **default** TAB does multiple things in different context: completion, indent line to align with the preceding line, insert TAB, etc. What you've configured is just one behavior of the TAB. It seems what you want from the normal TAB is to always insert two whitespace, is it? 

Pollen-mode modifies Emacs default TAB behavior only when lozenge precedes the cursor. I think you need to customize your emacs's default TAB behavior, which is documented in `indent-for-tab-command` function.

Don't hesitate to follow up if you need any help on configuration.

**Comment by jameskolce** [comment]
Thanks @lijunsong! I'll try to work with the current settings and see how it feels, so far is working fine in most parts but if I start getting problems then I'll look into the function you mentioned.

Thanks again!

**Comment by lijunsong** [comment]
Sure. I'd love to help if you need anything.
